### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by miguelmota** [hobochild/medium-posts#2]
JavaScript

```js
getPosts('miguelmota', 1).then(console.log)
```

Error

```bash
(node:73602) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/Volumes/hd2/Sandbox/authereum/packages/backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Volumes/hd2/Sandbox/authereum/packages/backend/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Volumes/hd2/Sandbox/authereum/packages/backend/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:73602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:73602) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by craigmulligan** [comment]
Hmm, it looks like they have put a recaptcha on the endpoint I was scraping https://medium.com/@the_economist/latest?format=json. 

Interestingly you can still get a few of the posts by using https://medium.com/@the_economist?format=json. So if you just need the user info and a couple of posts we could cut another version using that url?
